invigilator/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from home.views import *

urlpatterns = [
    path("",home,name="home"),
    path("home/", home, name="home"),
    path("admin/", admin.site.urls),
    path("register/", register, name="register"),
    path("login/", login_page, name="login"),
    path("logout/", logout_page, name="logout"),
    path("shifts/", shifts, name="shifts"),
    path("rooms/", rooms, name="rooms"),
    path("exams/", exams, name="exams"),
    path("buildings/", buildings, name="buildings"),
    path('summernote/', include('django_summernote.urls')),
    path("get-data/", get_data, name="get_data"),
    path("invigilators/", invigilators, name="invigillators"),
    path("examhallsessions/", examhallsessions, name="examhallsessions"),
    path("updateroom/<slug>/",update_room, name="update"),
    path("updatebuilding/<slug>/",update_building, name="update"),
    path("updateexam/<slug>/",update_exam, name="update"),
    path("updateinvigilator/<slug>/",update_invigilator, name="updateinvigilator"),
    path("updateexamhallsession/<slug>/",update_examhallsession, name="updateexamhallsession"),
    path("deleteroom/<slug>/",delete_room, name="deleteroom"),
    path("deletebuilding/<slug>/",delete_building, name="deletebuilding"),
    path("deleteinvigilator/<slug>/",delete_invigilator, name="deleteinvigilator"),
    path("deleteexam/<slug>/",delete_exam, name="deleteexam"),
    path("deleteexamhallsession/<slug>/",delete_examhallsession, name="deleteexamhallsession"),
    path("uploadcsv/", uploadcsv, name="uploadcsv"),
    path("generate-invigilators-excel/", generate_invigilators_excel, name="generate_invigilators_excel"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from autoslug import AutoSlugField


class Building(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug=AutoSlugField(populate_from='name',unique=True,null=True,default=None)
    def save(self, *args, **kwargs):
        # Convert attributes to uppercase
        self.name=self.name.upper()

        super().save(*args, **kwargs)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']

class Notice(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    published_date = models.DateTimeField()
    
    def __str__(self) -> str:
        return self.title

class Faculty(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Faculties"

class Room(models.Model):
    
    building = models.ForeignKey(
        Building, on_delete=models.CASCADE, related_name="rooms"
    )
    room_number = models.CharField(max_length=30)
    slug=AutoSlugField(populate_from='room_number',unique=True,null=True,default=None)

    @property
    def formatted_name(self):
        return f"{self.building.name} building room {self.room_number}"


    def __str__(self):
        return self.building.name + " building room " + self.room_number
    @staticmethod
    def get_available_rooms(date, shift):
        assigned_rooms= ExamHallSession.objects.filter(date=date, shift__in=shift).values('room')
        return Room.objects.all().exclude(id__in=assigned_rooms) 
 

    class Meta:
        unique_together = ["building", "room_number"]
        ordering = ["building__name"]


class Invigilator(models.Model):
    class GenderChoice(models.TextChoices):
        MALE = "MALE", "MALE"
        FEMALE = "FEMALE", "FEMALE"
        OTHERS = "OTHERS", "OTHERS"
    
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    gender = models.CharField(max_length=7, choices=GenderChoice.choices, default=GenderChoice.MALE.value)
    address = models.CharField(max_length=255,blank=True,null=True)
    phone_number = models.CharField(max_length=255,unique=True)
    post = models.CharField(max_length=255, blank=True,null=True)
    slug=AutoSlugField(populate_from='firstname',unique=True,null=True,default=None)
    def save(self, *args, **kwargs):
        # Convert attributes to uppercase
        self.firstname = self.firstname.upper()
        if self.lastname:
            self.lastname = self.lastname.upper()
        if self.post:
            self.post = self.post.upper()
        if self.address:
            self.address = self.address.upper()

        super().save(*args, **kwargs)


    def __str__(self):
        return self.firstname + " " + self.lastname

    @property
    def fullname(self):
        return f"{self.firstname} {self.lastname}"
 

    @staticmethod
    def get_available_invigilator(date, shift):
        assigned_invigilators = ExamHallSession.objects.filter(date=date, shift=shift).values('invigilators')
        return Invigilator.objects.all().exclude(id__in=assigned_invigilators) 


class Shift(models.Model):
    start=models.IntegerField()
    end=models.IntegerField()
    
    def __str__(self):
            return str(self.start) + "to" + str(self.end)

    
class Exam(models.Model):
    
    class Semester_typeChoice(models.TextChoices):
        ODD = "Odd", "odd"
        EVEN = "Even", "Even"
        NONE = "None", "None"

    
    class RegularOrBackChoices(models.TextChoices):
        REGULAR = "Regular", "Regular"
        BACK = "Back", "Back"
        NONE = "None", "None"


    class ShiftChoice(models.TextChoices):
        SIX = "6-9", "6-9"
        DAY = "12-12", "10-12"
    

    name = models.CharField(max_length=255)
    semester_type = models.CharField(max_length=50,choices=Semester_typeChoice.choices,default=Semester_typeChoice.ODD.value)
    regular_or_back = models.CharField(max_length=50,choices=RegularOrBackChoices.choices,default=RegularOrBackChoices.REGULAR.value)
    date = models.DateField()
    shift = models.ManyToManyField(Shift)
    slug=AutoSlugField(populate_from='name',unique=True,null=True,default=None)

    @staticmethod
    def get_unmanaged_exams(date, shift):
        managed_exams = ExamHallSession.objects.filter(date=date, shift__in=shift).values('exams')
        return Exam.objects.filter(date=date, shift=shift).exclude(id__in=managed_exams)    
    def __str__(self) -> str:
        return self.name +" "+ self.semester_type +" "+ self.regular_or_back

class ExamHallSession(models.Model):
    class ShiftChoice(models.TextChoices):
        MORNING = "Morning", "Morning"
        DAY = "Day", "Day"
    room = models.ForeignKey(
        Room, on_delete=models.CASCADE, related_name="exams"
    )
    exams = models.ManyToManyField(Exam)
    invigilators = models.ManyToManyField(Invigilator)
    shift = models.ForeignKey(Shift,on_delete=models.CASCADE,related_name="examhallsessions")
    date = models.DateField()
    slug=AutoSlugField(populate_from='date',unique=True,null=True,default=None)



    def __str__(self):
            return self.room

    class Meta:
        ordering= ["room__building"]
        # unique_together = ["room", "shift", "date"]

home/views.py
import json
import csv
from django.db.models import Q
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth import  login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.http import JsonResponse,HttpResponseRedirect
from django.shortcuts import redirect, render
import pandas as pd
from datetime import datetime
from itertools import groupby
from django.db.models.functions import Concat
from home.models import *
from .forms import BuildingForm, RoomForm, InvigilatorForm, ExamForm,ExamHallSessionForm,InvigilatorUploadForm,ExcelUploadForm,ShiftForm

# Create your views here.
def home(request):
    # examhallsession_qs = ExamHallSession.objects.all()
    # building=Building.objects.all()
    # return render(request,"home.html",{"examhallsessions":examhallsession_qs,"buildings":building} )
    buildings = Building.objects.all()
    building_exam_data = []

    for building in buildings:
        examhallsession_qs = ExamHallSession.objects.filter(room__building=building)
        building_data = {
            'building': building,
            'examhallsessions': examhallsession_qs,
        }
        if examhallsession_qs.count()>=1:
           building_exam_data.append(building_data)
    return render(request, "home.html", {"building_exam_data": building_exam_data})

def register(request):
    form=UserCreationForm()
    if request.method=="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
          form.save()
          messages.uccess(request,"Account created successfully")
          return HttpResponseRedirect(reverse("login"))
        else:
          messages.error(request,"Account not created! please try again")
    return render(request,"signup.html",{
        "form":form,
    })
        
    
 


def login_page(request):
    if request.method == "POST":
        form=AuthenticationForm(request,data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            return HttpResponseRedirect(reverse("home"))
        else:
            messages.error(request,"Login failed please check the username and password again")
    return render(request,"signin.html")



def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse("login"))




@login_required(login_url="/login/")
def shifts(request):
    form = ShiftForm()
    building_qs = Shift.objects.all()
    if request.GET.get("search"):
        search= request.GET.get("search")
        building_qs=building_qs.filter(
            Q(name__icontains=search)

            )
    context = {
        "form":form,
        "shifts":building_qs
    }
    if request.method == "POST":
        form=ShiftForm(request.POST)
        if form.is_valid():
           form.save()

    return render(request, "shift.html",context=context)

@login_required(login_url="/login/")
def buildings(request):
    form = BuildingForm()
    building_qs = Building.objects.all()
    if request.GET.get("search"):
        search= request.GET.get("search")
        building_qs=building_qs.filter(
            Q(name__icontains=search)

            )
    context = {
        "form":form,
        "buildings":building_qs
    }
    if request.method == "POST":
        form=BuildingForm(request.POST)
        if form.is_valid():
           form.save()

    return render(request, "building.html",context=context)


@login_required(login_url="/login/")
def rooms(request):
    form = RoomForm()
    room_qs = Room.objects.all()
    if request.GET.get("search"):
        search= request.GET.get("search")
        room_qs=room_qs.filter(
            Q(room_number__icontains=search)|
            Q(building__name__icontains=search)

            )
    context = {
        "form":form,
        "rooms":room_qs
    }
    if request.method == "POST":
        form=RoomForm(request.POST)
        if form.is_valid():
            try:
              form.save()
            except:
               messages.error(request,"This room is already in the list")   
        else:
            messages.error(request,"This room is already in the list")
    return render(request, "room.html",context=context)

@login_required(login_url="/login/")
def exams(request):
    form = ExamForm()
    exams = Exam.objects.all().order_by('name')
  
    if request.GET.get("search"):
        search= request.GET.get("search")
        exam_qs=exam_qs.filter(
            Q(name__icontains=search)|
            Q(semester_type__icontains=search)|
            Q(date__icontains=search)|
            Q(regular_or_back__icontains=search)
    



            )
    shifts =Shift.objects.all()


    if request.method == "POST":
        selected_dates_with_shifts = request.POST.get('selectedDatesWithShiftsField')
        dates_with_shifts_list = selected_dates_with_shifts.split(', ')

        for date_with_shift in dates_with_shifts_list:
            date, shiftranges= date_with_shift.split(': ')
            date_obj = datetime.strptime(date, '%Y-%m-%d').date()
            shifts_list=[]
            for shiftrange in shiftranges.split(','):
              try:
                shift_start,shift_end=shiftrange.split('-')
                shift_start = int(shift_start)
                shift_end = int(shift_end)
                id=Shift.objects.get(start=shift_start,end=shift_end).id
                shifts_list.append(id)
              except:
                  messages.error(request,"Please enter the shift")
            # Now, shifts will be a comma-separated string, you can further process it to create the ManyToMany relationship
            # shifts_list = [int(shift) for shift in shifts.split(',')]
            exam_exists = Exam.objects.filter(name=request.POST.get('name').upper(),
                                 date=date_obj, shift__in=shifts_list).exists()

            if not exam_exists:
            # Create Exam object with the selected date and shifts
                exam = Exam.objects.create(date=date_obj,
                                       name=request.POST.get('name').upper(),
                                       semester_type=request.POST.get('semester_type'),
                                        regular_or_back=request.POST.get('regular_or_back'),
                                        )
                exam.shift.set(shifts_list)
            else:
                messages.error(request,"This exam name of the given date and shift already exist")
    grouped_exams = {}
    for name, exams_group in groupby(exams, lambda x: x.name):
        grouped_exams[name] = list(exams_group) 
    context = {
        "form":form,
        "grouped_exams":grouped_exams,
        "shifts":shifts
    }



    return render(request, "exam.html",context=context)

@login_required(login_url="/login/")
def invigilators(request):
    form = InvigilatorForm()
    invigilator_qs = Invigilator.objects.all()

    search_name = request.GET.get("search_name")
    search_gender = request.GET.get("search_gender")
    search_address = request.GET.get("search_address")
    search_post = request.GET.get("search_post")

    if search_name:
        invigilator_qs = invigilator_qs.filter(Q(firstname__icontains=search_name.upper()) | Q(lastname__icontains=search_name))

    if search_gender:
        invigilator_qs = invigilator_qs.filter(gender=search_gender.upper())

    if search_address:
        invigilator_qs = invigilator_qs.filter(address__icontains=search_address.upper())

    if search_post:
        invigilator_qs = invigilator_qs.filter(post__icontains=search_post.upper())



            
    context = {
        "form":form,
        "invigilators":invigilator_qs
    }
    if request.method == "POST":
        form=InvigilatorForm(request.POST)
        if form.is_valid():
            try:
               form.save()
               messages.success(request,"Details saved successfully")
            except:
                messages.success(request,"Internal error")
        else:
            messages.error(request,"Person with this emal already exist")

            


    return render(request, "invigilator.html",context=context)

@login_required(login_url="/login/")
def examhallsessions(request):
    form = ExamHallSessionForm()
    examhallsession_qs = ExamHallSession.objects.all()
    buildings=Building.objects.all()
    if request.GET.get("search"):
        search= request.GET.get("search")
        examhallsession_qs=examhallsession_qs.filter(
            Q(exams__name__icontains=search)|
            Q(invigilators__firstname__icontains=search)|
            Q(date__icontains=search)
            )
    shifts=Shift.objects.all()
    context = {
        "form":form,
        "examhallsessions":examhallsession_qs,
        "buildings":buildings,
        "shifts":shifts
    }
    if request.method == "POST":
        form=ExamHallSessionForm(request.POST)
        try:
           if form.is_valid():
            messages.success(request,"Details saved successfully")
            form.save()
           else:
                messages.error(request,"Form not valid error")
        
        except:
            messages.error(request,"Internal error")

    return render(request, "examhallsession.html",context=context)


@login_required(login_url="/login/")
def get_data(request):
    date = request.GET.get('date')
    shift = request.GET.get('shift')
    building = request.GET.get('building')

    

    from django.db.models import F
    from django.db.models import CharField, Value

    exams=Exam.get_unmanaged_exams(date=date,shift=shift).values("id", "name")
    invigilators=Invigilator.get_available_invigilator(date=date,shift=shift).annotate(name=F("firstname")).values("id", "name")
    rooms=Room.get_available_rooms(date=date,shift=shift).annotate(name=F("room_number")

home/templates/addcsv.html
{% extends "base.html" %}

{% block content %}
    {% if message %}
    <ul class="messages">
       <li>{{message}}</li>
    </ul>
    {% endif %}

    <section class="vh-100" >
 
          <div class="row d-flex justify-content-center align-items-center h-10">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Upload  excel file in XLSX format</p>
      
                       <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
  <input type="submit" class="btn btn-success" value="Upload">
</form>
                    </div>
    
                  </div>
                </div>
              </div>
            </div>
          </div>
       
      </section>

{% endblock%}

home/templates/building.html
{% extends 'base.html' %}
{% block content %}


{% load crispy_forms_tags %}
  <form action="/buildings/" method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col-6">
    <div id="div_id_name" class="mb-3"> <label for="id_name" class="form-label requiredField">
        Name<span class="asteriskField">*</span> </label> <input type="text" name="name" maxlength="255"
        class="textinput form-control" required id="id_name"> </div>

    <input type="submit" class="btn btn-success" value="Create Building">
  </div>

  </form>
  <hr>

  <form class="d-flex mb-5 mt-5 mx-auto justify-content-center align-items-center" role="search">
    <input class="form-control me-2 w-25" type="search" name = "search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success " type="submit">Search</button>
  </form>
  <div class="d-flex flex-column justify-content-center align-items-center ">
    <h3>List of all the buildings</h3>
  </div>
  <hr>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for building in buildings %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{building.name}}</td>
      <td> 
      <a href="/updatebuilding/{{building.slug}}" class="text-decoration-none"><span class="material-symbols-outlined">
        edit
        </span>
      </a>
      <a href="/deletebuilding/{{building.slug}}" class="text-decoration-none">
        <span class="material-symbols-outlined">
          delete
          </span>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

home/templates/examhallsession.html
{% extends 'base.html' %}


{% block content %}

{% load crispy_forms_tags %}
<form action="/examhallsessions/" method="POST">

  <input type="hidden" name="csrfmiddlewaretoken"
    value="SAxVcmLc9wZwTAvFA8tXRIHBpyLc3FtmcTqk0zGOun0FgbnORfittqm58LhEzOCk">
  {% csrf_token %}

  <div id="div_id_building" class="mb-3"> <label for="id_building" class="form-label requiredField">
    Building<span class="asteriskField">*</span> </label> <select  name="building"
    class="select form-select" required id="id_building">
    <option value="" selected>---------</option>
    {% for building in buildings %}
    <option value="{{building.id}}">{{building.name}}</option>
    {% endfor %}

     


  </select> </div>

  <div id="div_id_date" class="mb-3"> <label for="id_date" class="form-label requiredField">
      Date<span class="asteriskField">*</span> </label> <input type="date" name="date" class="dateinput form-control"
      required id="id_date"> </div> 

  <div id="div_id_shift" class="mb-3"> <label for="id_shift" class="form-label requiredField">
    Shift<span class="asteriskField">*</span> </label> <select onchange="updateDropdowns(this.value)" name="shift"
    class="select form-select" required id="id_shift">
    <option value="" selected>---------</option>
    {% for shift in shifts %}
    <option value="{{shift.id}}">{{shift.start}} to {{shift.end}}</option>
    {% endfor %}

     


  </select> </div>

  <div id="div_id_room" class="mb-3"> <label for="id_room" class="form-label requiredField">
      Room<span class="asteriskField">*</span> </label> <select name="room" class="select form-select" required
      id="id_room">

    </select> </div>
  <div id="div_id_exams" class="mb-3"> <label for="id_exams" class="form-label requiredField">
      Exams<span class="asteriskField">*</span> </label> <select name="exams" class="selectmultiple form-select"
      required id="id_exams" multiple>


    </select> </div>
  <div id="div_id_invigilators" class="mb-3"> <label for="id_invigilators" class="form-label requiredField">
      Invigilators<span class="asteriskField">*</span> </label> <select name="invigilators"
      class="selectmultiple form-select" required id="id_invigilators" multiple>


    </select> </div>


  <input type="submit" class="btn btn-success" value="Create Examhallsession">
<div class="d-flex flex-column justify-content-center align-items-center ">
  <h3>List of all the exam sessions</h3>
</div>
<hr>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Shift</th>
      <th scope="col">Exams</th>
      <th scope="col">Type</th>

      <th scope="col">Room</th>
      <th scope="col">Invigilators</th>

    </tr>
  </thead>
  <tbody>
    {% for examhallsession in examhallsessions %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{examhallsession.date}}</td>
      <td>{{examhallsession.shift}}</td>
      <td>
        <ul>
          {% for exams in examhallsession.exams.all %}
          <li>
            {{exams.name}}
          </li>
          {% endfor %}
        </ul>
      </td>

      <td>
        <ul>
          {% for exams in examhallsession.exams.all %}
          <li>
            {{exams.regular_or_back}} {{exams.semester_type}} semester
          </li>
          {% endfor %}
        </ul>
      </td>      
      <td>{{examhallsession.room}}</td>

      <td>
        <ul>
          {% for invigilators in examhallsession.invigilators.all %}
          <li>
            {{invigilators}}
          </li>
          {% endfor %}
        </ul>
      </td>

      <td>
        
        {% comment %} <a href="/updateexamhallsession/{{examhallsession.slug}}" class="text-decoration-none"><span class="material-symbols-outlined">
          edit
          </span>
        </a> {% endcomment %}
        <a href="/deleteexamhallsession/{{examhallsession.slug}}" class="text-decoration-none">
          <span class="material-symbols-outlined">
            delete
            </span>
          </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  function updateDropdowns(selectedOption) {
    console.log('ajax called.');
    date = document.getElementById("id_date").value;
    building = document.getElementById("id_building").value;


    $.ajax({
      url: '/get-data/',
      type: 'GET',
      data: { 'date': date, 'shift': selectedOption, 'building': building },
      dataType: 'json',
      success: function (data) {
        exams = data.exams
        invigilators = data.invigilators
        rooms = data.rooms
        console.log("from ajax success");
        console.log(date);
        updateDependentDropdown('#id_exams', exams);
        updateDependentDropdown("#id_invigilators", invigilators);
        updateDependentDropdown("#id_room", rooms);
      },
      error: function () {
        console.log('Error occurred during Ajax request.');
      }
    });
  }

  function updateDependentDropdown(dropdownId, options) {
    var dropdown = $(dropdownId);
    dropdown.empty();
    console.log(options)
    $.each(options, function (index, option) {
      dropdown.append($('<option></option>').val(option.id).text(option.name));
    });
  }
</script>

{% endblock %}

home/templates/updatebuilding.html
{% extends 'base.html' %}
{% block content %}


{% load crispy_forms_tags %}
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}

    <input type="submit" class="btn btn-success" value="Update Building">
    </div>

</form>
<hr>

{% endblock %}

home/templates/updateexam.html
{% comment %} {% extends 'base.html' %}
{% block content %}


{% load crispy_forms_tags %}
<form  method="POST">
  {% csrf_token %}



  <div id="div_id_name" class="mb-3"> <label for="id_name" class="form-label requiredField">
      Name<span class="asteriskField">*</span> </label> <input type="text" name="name" maxlength="255"
      class="textinput form-control" required id="id_name"> </div>
  <div id="div_id_semester_type" class="mb-3"> <label for="id_semester_type" class="form-label requiredField">
      Semester type<span class="asteriskField">*</span> </label> <select name="semester_type" class="select form-select"
      id="id_semester_type">
      <option value="Odd" selected>odd</option>
      <option value="Even">Even</option>

    </select> </div>
  <div id="div_id_regular_or_back" class="mb-3"> <label for="id_regular_or_back" class="form-label requiredField">
      Regular or back<span class="asteriskField">*</span> </label> <select name="regular_or_back"
      class="select form-select" id="id_regular_or_back">
      <option value="Regular" selected>Regular</option>
      <option value="Back">Back</option>

    </select> </div>
  <div id="div_id_date" class="mb-3"> <label for="id_date" class="form-label requiredField">
      Date<span class="asteriskField">*</span> </label> <input type="date" name="date" class="dateinput form-control"
      required id="id_date"> </div>
  <div id="div_id_shift" class="mb-3"> <label for="id_shift" class="form-label requiredField">
      Shift<span class="asteriskField">*</span> </label> <select name="shift" class="select form-select" id="id_shift">
      <option value="Morning">Morning</option>
      <option value="Day" selected>Day</option>

    </select> </div>
  <div id="div_id_start_time" class="mb-3"> <label for="id_start_time" class="form-label requiredField">
      Start time<span class="asteriskField">*</span> </label> <input type="time" name="start_time"
      class="timeinput form-control" required id="id_start_time"> </div>
  <div id="div_id_end_time" class="mb-3"> <label for="id_end_time" class="form-label requiredField">
      End time<span class="asteriskField">*</span> </label> <input type="time" name="end_time"
      class="timeinput form-control" required id="id_end_time"> </div>

  <input type="submit" class="btn btn-success" value="Update Exam">
</form>

{% endblock %} {% endcomment %}

home/templates/updateexamhallsession.html
{% comment %} {% extends 'base.html' %}


{% block content %}

{% load crispy_forms_tags %}
<form  method="POST">

  <input type="hidden" name="csrfmiddlewaretoken"
    value="SAxVcmLc9wZwTAvFA8tXRIHBpyLc3FtmcTqk0zGOun0FgbnORfittqm58LhEzOCk">
  {% csrf_token %}


  <div id="div_id_room" class="mb-3"> <label for="id_room" class="form-label requiredField">
      Room<span class="asteriskField">*</span> </label> <select name="room" class="select form-select" required
      id="id_room">

    </select> </div>
  <div id="div_id_exams" class="mb-3"> <label for="id_exams" class="form-label requiredField">
      Exams<span class="asteriskField">*</span> </label> <select name="exams" class="selectmultiple form-select"
      required id="id_exams" multiple>


    </select> </div>
  <div id="div_id_invigilators" class="mb-3"> <label for="id_invigilators" class="form-label requiredField">
      Invigilators<span class="asteriskField">*</span> </label> <select name="invigilators"
      class="selectmultiple form-select" required id="id_invigilators" multiple>


    </select> </div>
  <div id="div_id_shift" class="mb-3"> <label for="id_shift" class="form-label requiredField">
      Shift<span class="asteriskField">*</span> </label> <select onchange="updateDropdowns(this.value)" name="shift"
      class="select form-select" required id="id_shift">
      <option value="" selected>---------</option>
      <option value="Morning">Morning</option>
      <option value="Day">Day</option>

    </select> </div>
  <div id="div_id_date" class="mb-3"> <label for="id_date" class="form-label requiredField">
      Date<span class="asteriskField">*</span> </label> <input type="date" name="date" class="dateinput form-control"
      required id="id_date"> </div> 

  <input type="submit" class="btn btn-success" value="Update Examhallsession">

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  function updateDropdowns(selectedOption) {
    console.log('ajax called.');
    date = document.getElementById("id_date").value;

    $.ajax({
      url: '/get-data/',
      type: 'GET',
      data: { 'date': date, 'shift': selectedOption },
      dataType: 'json',
      success: function (data) {
        exams = data.exams
        invigilators = data.invigilators
        rooms = data.rooms
        console.log("from ajax success");
        console.log(date);
        updateDependentDropdown('#id_exams', exams);
        updateDependentDropdown("#id_invigilators", invigilators);
        updateDependentDropdown("#id_room", rooms);
      },
      error: function () {
        console.log('Error occurred during Ajax request.');
      }
    });
  }

  function updateDependentDropdown(dropdownId, options) {
    var dropdown = $(dropdownId);
    dropdown.empty();
    console.log(options)
    $.each(options, function (index, option) {
      dropdown.append($('<option></option>').val(option.id).text(option.name));
    });
  }
</script>

{% endblock %} {% endcomment %}

home/templates/updateroom.html
{% extends 'base.html' %}


{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-primary" role="alert">
  <h3>{{message}}</h3>    
</div>
{% endfor%}
{% endif %}


{% load crispy_forms_tags %}
<form method="POST">
{% csrf_token %}

{{form|crispy}}
<input type="submit" class="btn btn-success" value="Update Room">
</form>


{% endblock %}